In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('loan_data.csv')
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001003   Male     Yes          1      Graduate            No   
1  LP001005   Male     Yes          0      Graduate           Yes   
2  LP001006   Male     Yes          0  Not Graduate            No   
3  LP001008   Male      No          0      Graduate            No   
4  LP001013   Male     Yes          0  Not Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             4583             1508.0       128.0             360.0   
1             3000                0.0        66.0             360.0   
2             2583             2358.0       120.0             360.0   
3             6000                0.0       141.0             360.0   
4             2333             1516.0        95.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Rural           N  
1             1.0         Urban           Y  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [3]:
df.isnull().sum()

Loan_ID               0
Gender                5
Married               0
Dependents            8
Education             0
Self_Employed        21
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term     11
Credit_History       30
Property_Area         0
Loan_Status           0
dtype: int64

In [4]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381 entries, 0 to 380
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            381 non-null    object 
 1   Gender             376 non-null    object 
 2   Married            381 non-null    object 
 3   Dependents         373 non-null    object 
 4   Education          381 non-null    object 
 5   Self_Employed      360 non-null    object 
 6   ApplicantIncome    381 non-null    int64  
 7   CoapplicantIncome  381 non-null    float64
 8   LoanAmount         381 non-null    float64
 9   Loan_Amount_Term   370 non-null    float64
 10  Credit_History     351 non-null    float64
 11  Property_Area      381 non-null    object 
 12  Loan_Status        381 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 38.8+ KB


In [5]:
df['Gender'].unique()

array(['Male', 'Female', nan], dtype=object)

In [6]:

df['Married'].unique()

array(['Yes', 'No'], dtype=object)

In [7]:
df['Dependents'].unique()

array(['1', '0', '2', '3+', nan], dtype=object)

In [8]:
df['Education'].unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [9]:
df['Self_Employed'].unique()

array(['No', 'Yes', nan], dtype=object)

In [10]:
df['ApplicantIncome'].unique()

array([4583, 3000, 2583, 6000, 2333, 3200, 2500, 1853, 1299, 4950, 3596,
       3510, 4887, 2600, 7660, 3365, 2799, 4226, 1442, 3750, 3167, 4692,
       3500, 1828, 3667, 3748, 3600, 1800, 2400, 3941, 4695, 3410, 5649,
       5821, 2645, 4000, 1928, 3086, 4230, 4616, 2708, 2132, 3366, 3357,
       3029, 4166, 7100, 4300, 1875, 4755, 1000, 3333, 3846, 3988, 2366,
       2958, 3273, 4133, 3620, 2484, 1977, 4188, 1759, 4288, 3052, 7333,
       2071, 5316, 2929, 5050, 2214, 2137, 2957, 3692, 2014, 2718, 3459,
       4895, 3316, 4200, 2698, 2330, 1538, 4860, 6277, 2281, 3254, 2980,
       1863, 3089, 9323, 2439, 2237, 1820, 3522, 4344, 3497, 2045, 1916,
       4600, 3625, 2178, 2383, 4885, 3858, 4191, 1907, 3416, 3917, 4408,
       3244, 3975, 2479, 3418, 3430, 5703, 3173, 3850,  150, 3727, 5000,
       4283, 2221, 4009, 2971, 6250, 4735, 2491, 3716, 3189, 3155, 3463,
       3812, 3315, 5819, 2510, 3406, 6050, 9703, 6608, 2882, 1809, 3427,
       6045, 5250, 4931, 2060, 7200, 5166, 4708, 28

In [11]:
df['CoapplicantIncome'].unique()

array([1.50800000e+03, 0.00000000e+00, 2.35800000e+03, 1.51600000e+03,
       7.00000000e+02, 1.84000000e+03, 2.84000000e+03, 1.08600000e+03,
       3.50000000e+03, 1.91100000e+03, 1.91700000e+03, 2.25300000e+03,
       1.04000000e+03, 2.08300000e+03, 1.66700000e+03, 1.33000000e+03,
       1.45900000e+03, 1.66800000e+03, 1.21300000e+03, 2.33600000e+03,
       3.44000000e+03, 2.27500000e+03, 1.64400000e+03, 1.16700000e+03,
       1.59100000e+03, 2.20000000e+03, 2.85900000e+03, 3.79600000e+03,
       2.25400000e+03, 1.87500000e+03, 3.02200000e+03, 2.16600000e+03,
       2.53100000e+03, 2.00000000e+03, 2.11800000e+03, 2.90000000e+03,
       1.82000000e+03, 2.30200000e+03, 9.97000000e+02, 3.54100000e+03,
       3.26300000e+03, 1.03000000e+03, 7.54000000e+02, 2.33300000e+03,
       1.39800000e+03, 8.98000000e+03, 1.92900000e+03, 1.43000000e+03,
       2.03400000e+03, 4.48600000e+03, 1.42500000e+03, 8.30000000e+02,
       1.04100000e+03, 1.28000000e+03, 3.33300000e+03, 1.76900000e+03,
      

In [12]:
df['LoanAmount'].unique()

array([128.,  66., 120., 141.,  95.,  70., 109., 114.,  17., 125., 100.,
        76., 133., 115., 104., 116., 112., 122., 110.,  35.,  74., 106.,
       144.,  80.,  47.,  75., 134.,  96.,  88.,  44.,  97., 135.,  99.,
       126., 136.,  81., 113., 130., 111.,  50., 131.,  25., 137.,  94.,
       139., 118.,  85.,  93., 102.,  84., 129.,  30.,  98., 121.,  63.,
        87., 101.,  67.,  73., 108.,  58.,  48.,  90., 124.,  55.,  59.,
       127.,  72.,  60., 138.,  42., 140., 123., 150.,  78.,  54.,  89.,
       143., 105., 132.,  56., 117.,  71.,  46., 103.,  45.,  65.,  53.,
        62., 148., 149., 119., 107., 145.,  26.,   9.,  36.,  61., 146.,
       142.,  40.])

In [13]:
df['Credit_History'].unique()

array([ 1., nan,  0.])

In [14]:
df['Property_Area'].unique()

array(['Rural', 'Urban', 'Semiurban'], dtype=object)